name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish V64CoreConsole/V64CoreConsole.csproj /p:DebugType=None /p:DebugSymbols=false -c Release -o release --nologo
    - name: Upload Content
      uses: actions/upload-artifact@v3
      with:
        name: v64cc-${{ github.run_number }}
        path: /home/runner/work/V64CoreConsole/V64CoreConsole/release/